### Get Request All members
GET http://localhost:8080/api/v1/members
Authorization: Bearer {{auth_token}}

### Get request a member with id
GET http://localhost:8080/api/v1/members/2

### Get request a member with name
GET http://localhost:8080/api/v1/members/nome/mateus

### Post Request for create a member
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
  "nome": "Mateus",
  "email": "mateus@mail.com",
  "cargo": "developer"
}

### Patch Request for update ONLY member information
PATCH http://localhost:8080/api/v1/members/3
Authorization: Basic admin 123
Content-Type: application/json


{
  "valorHora": 20.00
}

### Delete Request for erase memeber register
DELETE http://localhost:8080/api/v1/members/1