### Get all projects
GET http://localhost:8080/api/v1/projects
Authorization: Basic admin 123

### Get request for get project information by id
GET http://localhost:8080/api/v1/projects/1
Authorization: Basic admin 123

### Get request for get project information by name
GET http://localhost:8080/api/v1/projects/nome/project%20manager
Authorization: Basic admin 123

### Post Request for create a project
POST http://localhost:8080/api/v1/projects
Authorization: Basic admin 123
Content-Type: application/json

{
  "nome": "project manager",
  "descricao": "projeto para conclusao de TADS",
  "dataDeInicio": "2023-08-01",
  "dataDeConclusao": ""
}

### Patch request for update only project information
PATCH http://localhost:8080/api/v1/projects/2
Authorization: Basic admin 123
Content-Type: application/json

{
  "nome": "project manager api",
  "descricao": "api desenvolvida com spring boot",
  "dataDeInicio": "2023-01-30"
}

### Delete request for erase project information
DELETE http://localhost:8080/api/v1/projects/2
Authorization: Basic admin 123
